# Generated by Django 5.1.1 on 2024-09-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_category_course_certificate_enrollment_module_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='studentlist',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='studentlist',
            old_name='Register_Number',
            new_name='register_number',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
