# Generated by Django 5.1.1 on 2024-09-26 18:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_delete_user_rename_name_studentlist_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='answer',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='passing_grade',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='question',
        ),
        migrations.AddField(
            model_name='assessment',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='title',
            field=models.CharField(default='Untitled Assessment', max_length=255),
            preserve_default=False,
        ),
    ]
