# Generated by Django 5.1.1 on 2024-09-30 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_progress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='employee',
        ),
    ]
