# Generated by Django 5.1.1 on 2024-10-02 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('trainerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='role',
            field=models.ForeignKey(blank=True, help_text='The role for which this FAQ is relevant.', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
