# Generated by Django 5.1.1 on 2024-10-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerapp', '0003_trainerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainer_photos/'),
        ),
    ]
